import CardsHekken from '@/app/components/CardHekken';

export const cards = [
  <CardsHekken
    key={1}
    imgBgClass='bg-hek-card'
    nameProduct='ASH-3015'
    price='399'
    w={369}
    h={653}
  />,
  <CardsHekken
    key={2}
    imgBgClass='bg-hek-card'
    nameProduct='ASH-2070'
    price='499'
    w={369}
    h={653}
  />,
  <CardsHekken
    key={3}
    imgBgClass='bg-hek-card'
    nameProduct='ASH-R25'
    price='299'
    w={369}
    h={653}
  />,
  <CardsHekken
    key={1}
    imgBgClass='bg-hek-card'
    nameProduct='ASH-3015'
    price='399'
    w={369}
    h={653}
  />,
  <CardsHekken
    key={2}
    imgBgClass='bg-hek-card'
    nameProduct='ASH-2070'
    price='499'
    w={369}
    h={653}
  />,
  <CardsHekken
    key={3}
    imgBgClass='bg-hek-card'
    nameProduct='ASH-R25'
    price='299'
    w={369}
    h={653}
  />,

  <CardsHekken
    key={1}
    imgBgClass='bg-hek-card'
    nameProduct='ASH-3015'
    price='399'
    w={369}
    h={653}
  />,
  <CardsHekken
    key={2}
    imgBgClass='bg-hek-card'
    nameProduct='ASH-2070'
    price='499'
    w={369}
    h={653}
  />,
  <CardsHekken
    key={3}
    imgBgClass='bg-hek-card'
    nameProduct='ASH-R25'
    price='299'
    w={369}
    h={653}
  />,
];
